# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cpcs-test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Nuke'

  # Pods for cpcs-test

  target 'cpcs-testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cpcs-testUITests' do
    # Pods for testing
  end

end
